---
variables:
  GET_SOURCES_ATTEMPTS: "3"
  GIT_SUBMODULE_STRATEGY: "recursive"

stages:
  - build
  - release


build default:
  image: rust
  stage: build
  dependencies: []
  before_script:
    - export CARGO_HOME="${PWD}/.cargo_cache"
  script:
    - cargo build --release
  cache:
    paths:
      - .cargo_cache/

release static:
  image: rust
  stage: release
  dependencies: []
  before_script:
    - apt-get update -qq && apt-get install -y -qq musl-dev musl-tools
    - rustup target add x86_64-unknown-linux-musl
    - export CARGO_HOME="${PWD}/.cargo_cache"
  script:
    - cargo build --release --target=x86_64-unknown-linux-musl
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/junit2md
  cache:
    paths:
      - .cargo_cache/
