[package]
name = "junit2md"
version = "0.1.0"
authors = ["Oleg `Kanedias` Chernovskiy <kanedias@keemail.me>"]
edition = "2018"

[dependencies]
serde-xml-rs = "0.3.1"
serde = "1.0"
serde_derive = "1.0"
clap = "2.33.0"
failure = "0.1.5"